# Generated by Django 4.2.9 on 2026-10-02 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakePacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packet_no', models.CharField(max_length=40, unique=True, verbose_name='收件编号')),
                ('doc_type', models.CharField(choices=[('appraisal_report', '鉴定报告'), ('handover_document', '移交文书')], max_length=30, verbose_name='材料类别')),
                ('title', models.CharField(max_length=200, verbose_name='收件标题')),
                ('biz_type', models.CharField(max_length=50, verbose_name='关联业务类型')),
                ('biz_ref', models.CharField(max_length=100, verbose_name='关联业务标识')),
                ('biz_label', models.CharField(blank=True, max_length=200, verbose_name='关联业务说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intake_packets', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
            ],
            options={
                'verbose_name': '收件登记',
                'verbose_name_plural': '收件登记',
                'db_table': 'cd_intake_packet',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntakeMutex',
            fields=[
                ('packet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mutex', serialize=False, to='custody.intakepacket', verbose_name='收件登记')),
                ('touched_at', models.DateTimeField(auto_now=True, verbose_name='最近锁定时间')),
            ],
            options={
                'verbose_name': '收件版本锁',
                'verbose_name_plural': '收件版本锁',
                'db_table': 'cd_intake_mutex',
            },
        ),
        migrations.CreateModel(
            name='IntakeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField(verbose_name='版本号')),
                ('change_type', models.CharField(choices=[('initial', '首次收件'), ('supplement', '补件'), ('revocation', '作废')], default='initial', max_length=20, verbose_name='变更性质')),
                ('status', models.CharField(choices=[('active', '有效'), ('superseded', '已失效'), ('revoked', '已作废')], default='active', max_length=20, verbose_name='版本状态')),
                ('submitted_by_name', models.CharField(max_length=50, verbose_name='提交人姓名（快照）')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('manifest_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='整单清单哈希')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='custody.intakepacket', verbose_name='收件登记')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intake_versions', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '收件版本',
                'verbose_name_plural': '收件版本',
                'db_table': 'cd_intake_version',
                'ordering': ['packet_id', '-version_no'],
            },
        ),
        migrations.CreateModel(
            name='IntakeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_size', models.PositiveBigIntegerField(verbose_name='文件大小（字节）')),
                ('sha256', models.CharField(max_length=64, verbose_name='SHA-256')),
                ('submitted_by_name', models.CharField(max_length=50, verbose_name='提交人姓名（快照）')),
                ('biz_type', models.CharField(max_length=50, verbose_name='关联业务类型')),
                ('biz_ref', models.CharField(max_length=100, verbose_name='关联业务标识')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='接收时间')),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='custody.intakepacket', verbose_name='收件登记')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intake_attachments', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='custody.intakeversion', verbose_name='所属版本')),
            ],
            options={
                'verbose_name': '收件文件摘要',
                'verbose_name_plural': '收件文件摘要',
                'db_table': 'cd_intake_attachment',
                'ordering': ['packet_id', '-version_id', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='intakeversion',
            constraint=models.UniqueConstraint(fields=('packet', 'version_no'), name='cd_uniq_packet_version_no'),
        ),
        migrations.AddConstraint(
            model_name='intakeattachment',
            constraint=models.UniqueConstraint(fields=('packet', 'sha256'), name='cd_uniq_packet_sha256'),
        ),
    ]
