# Generated by Django 4.2.9 on 2026-10-02 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustodyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_no', models.CharField(max_length=32, unique=True, verbose_name='业务编号')),
                ('doc_type', models.CharField(choices=[('appraisal', '鉴定报告'), ('transfer', '移交文书')], max_length=20, verbose_name='文书类型')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '业务记录',
                'verbose_name_plural': '业务记录',
                'db_table': 'doc_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManifestVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField(verbose_name='版本号')),
                ('reason', models.CharField(choices=[('initial', '首次收件'), ('supplement', '补件'), ('invalidation', '作废')], max_length=20, verbose_name='版本原因')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('doc_no_snapshot', models.CharField(max_length=32, verbose_name='业务编号快照')),
                ('doc_title_snapshot', models.CharField(max_length=100, verbose_name='业务标题快照')),
                ('submitted_by_name', models.CharField(max_length=50, verbose_name='提交人快照')),
                ('prev_hash', models.CharField(blank=True, max_length=64, verbose_name='上一版本清单哈希')),
                ('manifest_hash', models.CharField(max_length=64, verbose_name='清单哈希')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='documents.custodydocument', verbose_name='业务记录')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_manifests', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '清单版本',
                'verbose_name_plural': '清单版本',
                'db_table': 'doc_manifest_version',
                'ordering': ['-created_at'],
                'unique_together': {('document', 'version_no')},
            },
        ),
        migrations.CreateModel(
            name='ManifestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add', '登记'), ('void', '作废')], default='add', max_length=10, verbose_name='动作')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小（字节）')),
                ('sha256', models.CharField(max_length=64, verbose_name='SHA-256摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='documents.manifestversion', verbose_name='清单版本')),
                ('voids', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_by', to='documents.manifestentry', verbose_name='作废目标')),
            ],
            options={
                'verbose_name': '清单条目',
                'verbose_name_plural': '清单条目',
                'db_table': 'doc_manifest_entry',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['sha256'], name='doc_manifes_sha256_c5d349_idx')],
            },
        ),
    ]
